---
- name: Install Docker
  import_role:
    name: egvimo.misc.installer
  vars:
    installer_packages:
      - docker

- name: Create Docker config directory
  ansible.builtin.file:
    path: /etc/docker
    owner: root
    group: root
    mode: "0755"
    state: directory
  become: true

- name: Copy Docker daemon config
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Create Docker log directory
  ansible.builtin.file:
    path: /var/log/docker
    owner: root
    group: docker
    mode: "0770"
    state: directory
  become: true

- name: Copy Docker daemon start script
  ansible.builtin.copy:
    src: start-dockerd.sh
    dest: /usr/local/bin/start-dockerd
    owner: root
    group: root
    mode: "0755"
  become: true
