---
- name: "Get profile path"
  ansible.windows.win_shell: $PROFILE
  changed_when: false
  check_mode: false
  register: profile_path

- name: "Add Docker functions to {{ profile_path.stdout | trim }}"
  community.windows.win_lineinfile:
    path: "{{ profile_path.stdout | trim }}"
    create: true
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
  loop:
    - {
        line: "function docker { wsl -d Ubuntu docker @Args }",
        regexp: '^function docker \{',
      }
    - {
        line: "function dockerd { wsl -d Ubuntu start-dockerd }",
        regexp: '^function dockerd \{',
      }
