---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      include_role:
        name: dotfiles
      vars:
        ansible_user: root
        dotfiles:
          - aliases
          - gotify_cli
          - inputrc
          - starship
