---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: dotfiles
      vars:
        ansible_user: root
        dotfiles:  # noqa var-naming[no-role-prefix]
          - aliases
          - inputrc
          - starship
