namespace: egvimo
name: misc
version: "0.9.0"
description: Collection of miscellaneous roles

authors:
  - egvimo

readme: README.md
license_file: LICENSE

tags:
  - docker
  - git_server
  - gitea
  - installer
  - jdownloader
  - k3s
  - minidlna
  - pi_hole
  - raspberry
  - system

repository: https://github.com/egvimo/ansible-collection-misc
documentation: https://github.com/egvimo/ansible-collection-misc
homepage: https://github.com/egvimo/ansible-collection-misc
issues: https://github.com/egvimo/ansible-collection-misc/issues
