namespace: egvimo
name: misc
version: "0.12.0"
description: Collection of miscellaneous roles

authors:
  - egvimo

readme: README.md
license_file: LICENSE

tags:
  - dotfiles
  - gnome
  - installer
  - raspberry

repository: https://github.com/egvimo/ansible-collection-misc
documentation: https://github.com/egvimo/ansible-collection-misc
homepage: https://github.com/egvimo/ansible-collection-misc
issues: https://github.com/egvimo/ansible-collection-misc/issues
