---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Build the collection
      command: ansible-galaxy collection build
      args:
        creates: "egvimo-misc-{{ version }}.tar.gz"

    - name: Publish the collection
      command: "ansible-galaxy collection publish egvimo-misc-{{ version }}.tar.gz --token='{{ lookup('env', 'ANSIBLE_GALAXY_API_KEY') }}'"
      register: publish_result
      changed_when: "publish_result.rc == 0"
