---
- name: Ensure bash-completion is installed
  ansible.builtin.apt:
    name: bash-completion
    update_cache: true
    state: present
  become: true

- name: Ensure bash-completion directory exists
  ansible.builtin.file:
    path: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create kubectl completion file
  ansible.builtin.shell: kubectl completion bash > kubectl
  args:
    chdir: /etc/bash_completion.d
    creates: /etc/bash_completion.d/kubectl
  become: true
