---
- name: Install kubectl via Scoop
  community.windows.win_scoop:
    name: kubectl
    state: present

- name: Get profile path
  ansible.windows.win_shell: $ENV:USERPROFILE
  changed_when: false
  register: userprofile_path

- name: "Ensure .kube directory exists in {{ userprofile_path.stdout | trim }}"
  ansible.windows.win_file:
    path: "{{ userprofile_path.stdout | trim }}\\.kube"
    state: directory
