---
- name: "Install via Scoop - {{ _package }}"
  community.windows.win_scoop:
    name: kubectl
    state: present

- name: "Get profile path - {{ _package }}"
  ansible.windows.win_shell: $ENV:USERPROFILE
  changed_when: false
  check_mode: false
  register: userprofile_path

- name: "Ensure .kube directory exists in {{ userprofile_path.stdout | trim }} - {{ _package }}" # noqa name
  ansible.windows.win_file:
    path: "{{ userprofile_path.stdout | trim }}\\.kube"
    state: directory
