---
- block:
    - name: "[{{ installer_package }}] Get checksums for archive"
      ansible.builtin.uri:
        url: "{{ k3d_releases_url }}/sha256sum.txt"
        return_content: true
      check_mode: false
      register: k3d_checksums

    - name: "[{{ installer_package }}] Extract checksum for archive"
      ansible.builtin.set_fact:
        k3d_checksum: "{{ k3d_checksums.content | regex_search(k3d_checksum_regex, '\\1', multiline=true) }}"
      vars:
        k3d_checksum_regex: "^([a-z0-9]+).+?{{ k3d_binary }}$"

    - name: "[{{ installer_package }}] Download binary"
      ansible.builtin.get_url:
        url: "{{ k3d_releases_url }}/{{ k3d_binary }}"
        checksum: "sha256:{{ k3d_checksum }}"
        dest: /usr/local/bin/k3d
        owner: root
        group: root
        mode: "0755"
      become: true
  vars:
    k3d_releases_url: "https://github.com/rancher/k3d/releases/{{ 'download/' + installer_k3d_version if installer_k3d_version is defined else 'latest/download' }}"
    k3d_binary: "k3d-linux-{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
