---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: system

    - name: Include role
      ansible.builtin.include_role:
        name: system
      vars:
        system_packages_to_remove:
          - git
          - gnupg
        system_packages_to_install:
          - screen
