---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:latest
provisioner:
  name: ansible
  prepare: prepare.yml
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
