---
- name: "[{{ dotfile }}] Check if destination directory exists"
  ansible.builtin.stat:
    path: "{{ dotfile_config.destination | dirname }}"
  register: destination_directory

- name: "[{{ dotfile }}] Create directory if missing"
  ansible.builtin.file:
    path: "{{ dotfile_config.destination | dirname }}"
    state: directory
    mode: '0755' # TODO Use mode from config +x
  when: not destination_directory.stat.exists

- name: "[{{ dotfile }}] Template dotfile"
  ansible.builtin.template:
    src: "{{ dotfile_config.filename }}"
    dest: "{{ dotfile_config.destination }}"
    owner: "{{ dotfile_config.user | default(ansible_user) }}"
    mode: "{{ dotfile_config.mode | default('0644') }}"
  when: dotfile_config.filename.endswith('.j2')

- name: "[{{ dotfile }}] Copy dotfile"
  ansible.builtin.copy:
    src: "{{ dotfile_config.filename }}"
    dest: "{{ dotfile_config.destination }}"
    owner: "{{ dotfile_config.user | default(ansible_user) }}"
    mode: "{{ dotfile_config.mode | default('0644') }}"
  when: not dotfile_config.filename.endswith('.j2')
