---
- name: Copy dotfiles
  tags: dotfiles
  block:
    - name: Copy dotfiles
      ansible.builtin.include_tasks: copy_dotfile.yml
      loop: "{{ dotfiles }}"
      loop_control:
        loop_var: _dotfile
