---
- name: "[{{ dotfile }}] Check if destination directory exists"
  ansible.builtin.win_stat:
    path: "{{ dotfile_config.destination | dirname }}"
  register: destination_directory

- name: "[{{ dotfile }}] Create directory if missing"
  ansible.builtin.win_file:
    path: "{{ dotfile_config.destination | dirname }}"
    state: directory
  when: not destination_directory.stat.exists

- name: "[{{ dotfile }}] Template dotfile"
  ansible.builtin.win_template:
    src: "{{ dotfile_config.filename }}"
    dest: "{{ dotfile_config.destination }}"
  when: dotfile_config.filename.endswith('.j2')

- name: "[{{ dotfile }}] Copy dotfile"
  ansible.builtin.win_copy:
    src: "{{ dotfile_config.filename }}"
    dest: "{{ dotfile_config.destination }}"
  when: not dotfile_config.filename.endswith('.j2')
