---
- name: "[{{ _dotfile }}] Check if destination directory exists"
  ansible.builtin.win_stat:
    path: "{{ _dotfile_config.destination | dirname }}"
  register: _destination_directory

- name: "[{{ _dotfile }}] Create directory if missing"
  ansible.builtin.win_file:
    path: "{{ _dotfile_config.destination | dirname }}"
    state: directory
  when: not _destination_directory.stat.exists

- name: "[{{ _dotfile }}] Template dotfile"
  ansible.builtin.win_template:
    src: "{{ _dotfile_config.filename }}"
    dest: "{{ _dotfile_config.destination }}"
  when: _dotfile_config.filename.endswith('.j2')

- name: "[{{ _dotfile }}] Copy dotfile"
  ansible.builtin.win_copy:
    src: "{{ _dotfile_config.filename }}"
    dest: "{{ _dotfile_config.destination }}"
  when: not _dotfile_config.filename.endswith('.j2')
