---
- name: "Check for separate tasks - {{ _package }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ _package }}/{{ ansible_os_family | lower }}.yml"
  delegate_to: localhost
  register: _task_path

- name: "Append to custom packages - {{ _package }}"
  ansible.builtin.set_fact:
    _packages_custom: "{{ _packages_custom + [_package] }}"
  when: _task_path.stat.exists

- name: "Include OS specific sorter - {{ _package }}"
  include_tasks: "sort/{{ ansible_os_family | lower }}.yml"
  when: not _task_path.stat.exists
