---
- name: Prepare
  hosts: all
  gather_facts: False
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - dbus
          - dconf-cli
        update_cache: yes
        state: present
