---
- name: Prepare
  hosts: all
  gather_facts: False
  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - dbus
          - dconf
        state: present
      become: true
