---
- block:
    - name: Remove packages
      ansible.builtin.apt:
        pkg: "{{ system_packages_to_remove }}"
        state: absent

    - name: Install packages
      ansible.builtin.apt:
        pkg: "{{ system_packages_to_install }}"
        state: present
  become: yes
  tags: system_packages
