---
- name: "Check for separate tasks for '{{ installer_package }}'"
  local_action: ansible.builtin.stat path="{{ role_path }}/tasks/{{ installer_package }}"
  register: task_path

- name: "Include custom installer tasks for '{{ installer_package }}'"
  include_tasks: "{{ installer_package }}/main.yml"
  when: task_path.stat.exists

- name: "Include OS specific tasks for '{{ installer_package }}'"
  include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: not task_path.stat.exists
