---
- name: Install packages
  include_tasks:
    file: install_package.yml
    apply:
      tags: installer
  loop: "{{ installer_packages }}"
  loop_control:
    loop_var: installer_package
  tags: installer
