---
- block:
    - name: Prepare package lists
      ansible.builtin.set_fact:
        _packages: "{{ installer_packages.split(',') if installer_packages is string else installer_packages | default([]) }}"
        _packages_custom: []
        _packages_apt: "{{ installer_packages_apt.split(',') if installer_packages_apt is string else installer_packages_apt | default([]) }}"
        _packages_scoop: "{{ installer_packages_scoop.split(',') if installer_packages_scoop is string else installer_packages_scoop | default([]) }}"

    - name: Sort packages
      include_tasks:
        file: sort/main.yml
        apply:
          tags: installer
      loop: "{{ _packages }}"
      loop_control:
        loop_var: _package

    - name: Include custom package installer
      include_tasks:
        file: "{{ _package }}/{{ ansible_os_family | lower }}.yml"
        apply:
          tags: installer
      loop: "{{ _packages_custom }}"
      loop_control:
        loop_var: _package
      when: _packages_custom | length

    - name: Include OS specific installer
      include_tasks:
        file: "{{ ansible_os_family | lower }}.yml"
        apply:
          tags: installer

  tags: installer
