---
# TODO Run this only once for a play
- name: "[{{ installer_package }}] Ensure additional buckets are present"
  community.windows.win_scoop_bucket:
    name: "{{ item }}"
    state: present
  loop:
    - extras
    - java

- name: "[{{ installer_package }}] Install via Scoop"
  community.windows.win_scoop:
    name: "{{ installer_package }}"
    state: present
