---
- name: "[{{ _package }}] Gather package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "[{{ _package }}] Install"
  ansible.builtin.apt:
    deb: "https://github.com/Peltoche/lsd/releases/download/{{ version }}/lsd_{{ version }}_{{ architecture }}.deb"
    update_cache: true
  become: true
  when: "'lsd' not in ansible_facts.packages"
  vars:
    architecture: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    version: "0.20.1"
