---
- name: Set background picture
  tags: gnome_background
  block:
    - name: "Ensure required packages for dconf module are installed - background"
      ansible.builtin.apt:
        name: python3-psutil
        update_cache: true
        cache_valid_time: 3600
        state: present
      become: true
      when: ansible_os_family == 'Debian'

    - name: "Ensure required packages for dconf module are installed - background"
      ansible.builtin.dnf:
        name: python3-psutil
        state: present
      become: true
      when: ansible_os_family == 'RedHat'

    - name: "Ensure directory exists - background"
      ansible.builtin.file:
        path: /usr/share/backgrounds
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: "Copy picture - background"
      ansible.builtin.copy:
        src: wood.png
        dest: /usr/share/backgrounds/wood.png
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: "Set picture - background"
      community.general.dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/wood.png'"
        state: present
