---
- name: Run Gnome tasks
  tags: gnome
  block:
    - name: Include Gnome tasks
      ansible.builtin.include_tasks: "{{ _tasks }}.yml"
      loop:
        - background
        - extensions
      loop_control:
        loop_var: _tasks
