---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      include_role:
        name: helper
        tasks_from: create_user
      vars:
        helper_user_id: alice
        helper_user_name: Alice
    - name: Include role
      include_role:
        name: helper
        tasks_from: create_user
      vars:
        helper_user_id: bob
    - name: Include role
      include_role:
        name: helper
        tasks_from: create_user
      vars:
        helper_user_id: charlie
        helper_add_group_to: bob
