---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
