---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: geerlingguy/docker-debian10-ansible:latest
    pre_build_image: true
  - name: fedora
    image: geerlingguy/docker-fedora36-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
