---
- name: Install Restic
  vars:
    restic_releases_url: https://github.com/restic/restic/releases/latest/download
    restic_version: "0.14.0"
    restic_archive_name: "restic_{{ restic_version }}_linux_{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}.bz2"
  block:
    - name: "Get checksums for archive - {{ _package }}"
      ansible.builtin.uri:
        url: "{{ restic_releases_url }}/SHA256SUMS"
        return_content: true
      check_mode: false
      register: restic_checksums

    - name: "Extract checksum for archive - {{ _package }}"
      ansible.builtin.set_fact:
        restic_checksum: "{{ restic_checksums.content | regex_search(restic_checksum_regex, '\\1', multiline=true) }}"
      vars:
        restic_checksum_regex: "^([a-z0-9]+)  {{ restic_archive_name }}$"

    - name: "Download archive - {{ _package }}"
      ansible.builtin.get_url:
        url: "{{ restic_releases_url }}/{{ restic_archive_name }}"
        checksum: "sha256:{{ restic_checksum }}"
        dest: /tmp/restic.bz2
        mode: "0666"
      become: true
      register: restic_archive

# - name: "Extract archive - {{ _package }}"
#   ansible.builtin.unarchive:
#     src: /tmp/restic.bz2
#     dest: /usr/local/bin
#     remote_src: true
#     owner: root
#     group: root
#     mode: "0755"
#   become: true
#   when: restic_archive.changed # noqa no-handler

- name: "Create completion file - {{ _package }}"
  ansible.builtin.command: restic generate --bash-completion /etc/bash_completion.d/restic
  args:
    chdir: /etc/bash_completion.d
    creates: /etc/bash_completion.d/restic
  become: true
