---
galaxy_info:
  role_name: docker_wsl
  author: egvimo
  description: Install and configure Docker inside WSL2 to use it under Windows

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - docker
    - wsl
    - linux
    - windows
