---
- name: "[{{ _package }}] Ensure gpg is installed"
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: "[{{ _package }}] Add key"
  ansible.builtin.apt_key:
    url: "{{ apt_key_url }}"
    state: present
  become: true

- name: "[{{ _package }}] Add repository"
  ansible.builtin.apt_repository:
    repo: "{{ apt_repository }}"
    filename: "{{ apt_repository_name }}"
    state: present
  become: true

- name: "[{{ _package }}] Install"
  ansible.builtin.apt:
    name: "{{ apt_package_name }}"
    state: present
    update_cache: yes
  become: true
  when: apt_install is defined and apt_install

- name: "[{{ _package }}] Append to apt packages"
  ansible.builtin.set_fact:
    _packages_apt: "{{ _packages_apt + [apt_package_name] }}"
  when: apt_install is not defined or not apt_install
