---
- name: "Ensure gpg is installed - {{ _package }}"
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: "Add key - {{ _package }}"
  ansible.builtin.apt_key:
    url: "{{ apt_key_url }}"
    state: present
  become: true

- name: "Add repository - {{ _package }}"
  ansible.builtin.apt_repository:
    repo: "{{ apt_repository }}"
    filename: "{{ apt_repository_name }}"
    state: present
  become: true

- name: "Install {{ _package }}"
  ansible.builtin.apt:
    name: "{{ apt_package_name }}"
    state: present
    update_cache: yes
  become: true
  when: apt_install is defined and apt_install

- name: "Append to apt packages - {{ _package }}"
  ansible.builtin.set_fact:
    _packages_apt: "{{ _packages_apt + [apt_package_name] }}"
  when: apt_install is not defined or not apt_install
