---
- name: Install bash completion
  vars:
    completion_dir: /etc/bash_completion.d
  block:
    - name: "Ensure bash-completion is installed - {{ _package }}"
      ansible.builtin.apt:
        name: bash-completion
        update_cache: true
        cache_valid_time: 3600
        state: present
      become: true

    - name: "Ensure bash-completion directory exists - {{ _package }}"
      ansible.builtin.file:
        path: "{{ completion_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      become: true

    - name: "Create {{ name }} completion file - {{ _package }}" # noqa name
      ansible.builtin.shell: "{{ command }} > {{ name }}"
      args:
        chdir: "{{ completion_dir }}"
        creates: "{{ completion_dir }}/{{ name }}"
      become: true
