---
- block:
    - name: "[{{ installer_package }}] Ensure bash-completion is installed"
      ansible.builtin.apt:
        name: bash-completion
        update_cache: true
        state: present
      become: true

    - name: "[{{ installer_package }}] Ensure bash-completion directory exists"
      ansible.builtin.file:
        path: "{{ completion_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      become: true

    - name: "[{{ installer_package }}] Create {{ name }} completion file"
      ansible.builtin.shell: "{{ command }} > {{ name }}"
      args:
        chdir: "{{ completion_dir }}"
        creates: "{{ completion_dir }}/{{ name }}"
      become: true
  vars:
    completion_dir: /etc/bash_completion.d
