---
galaxy_info:
  role_name: minidlna
  author: egvimo
  description: Installation of ReadyMedia (formerly known as MiniDLNA) as Docker container

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all

  galaxy_tags:
    - readymedia
    - minidlna
