---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: installer
      vars:
        ansible_user: root
        installer_packages:
          - bat
          #- brave
          - gotify-cli
          - helm
          #- k3s
          - k9s
          - kubectl
          - lf
          - lsd
          - rclone
          #- restic
          - screen
          - starship
          - syncthing
          #- vscode
