---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: installer
      vars:
        ansible_user: root
        installer_packages:
          #- brave
          - gotify-cli
          - helm
          - k9s
          - kubectl
          - lsd
          - screen
          - starship
          #- vscode
