---
- name: "Get checksum for archive - {{ _package }}"
  ansible.builtin.uri:
    url: "https://github.com/starship/starship/releases/latest/download/starship-{{ ansible_architecture }}-unknown-linux-musl.tar.gz.sha256"
    return_content: true
  check_mode: false
  register: starship_checksum

- name: "Download archive - {{ _package }}"
  ansible.builtin.get_url:
    url: "https://github.com/starship/starship/releases/latest/download/starship-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    checksum: "sha256:{{ starship_checksum.content }}"
    dest: /tmp/starship.tar.gz
    mode: "0666"
  become: true
  register: starship_archive

- name: "Extract archive - {{ _package }}"
  ansible.builtin.unarchive:
    src: /tmp/starship.tar.gz
    dest: /usr/local/bin
    remote_src: true
    owner: root
    group: root
    mode: "0755"
  become: true
  when: starship_archive.changed # noqa no-handler

- name: "Add configuration to .bashrc for user {{ ansible_user }} - {{ _package }}" # noqa name
  ansible.builtin.lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    create: true
    line: 'eval "$(starship init bash)"'
    regexp: '^eval "$(starship init bash)"'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
