---
- name: Install Starship via Scoop
  community.windows.win_scoop:
    name: starship
    state: present

- name: Get profile path
  ansible.windows.win_shell: $PROFILE
  changed_when: false
  register: profile_path

- name: "Add Starship configuration to {{ profile_path.stdout | trim }}"
  community.windows.win_lineinfile:
    path: "{{ profile_path.stdout | trim }}"
    create: yes
    line: "Invoke-Expression (&starship init powershell)"
    regexp: '^Invoke-Expression \(&starship init powershell\)'
    state: present
