---
- name: "Install via Scoop - {{ _package }}"
  community.windows.win_scoop:
    name: starship
    state: present

- name: "Get profile path - {{ _package }}"
  ansible.windows.win_shell: $PROFILE
  changed_when: false
  check_mode: false
  register: profile_path

- name: "Add configuration to {{ profile_path.stdout | trim }} - {{ _package }}" # noqa name
  community.windows.win_lineinfile:
    path: "{{ profile_path.stdout | trim }}"
    create: true
    line: "Invoke-Expression (&starship init powershell)"
    regexp: '^Invoke-Expression \(&starship init powershell\)'
    state: present
