---
- block:
    - name: Update raspi-config to latest version
      ansible.builtin.apt:
        name: raspi-config
        update_cache: true
        cache_valid_time: 3600
        state: latest

    - name: Change locale
      ansible.builtin.command: "raspi-config nonint do_change_locale {{ raspberry_locale }}"

    - name: Change timezone
      ansible.builtin.command: "raspi-config nonint do_change_timezone {{ raspberry_timezone }}"

    - name: Change keyboard layout
      ansible.builtin.command: "raspi-config nonint do_configure_keyboard {{ raspberry_keyboard_layout }}"

    - name: Set WLAN country
      ansible.builtin.command: "raspi-config nonint do_wifi_country {{ raspberry_wlan_country }}"

    - name: Check if FS is expandable
      ansible.builtin.command: raspi-config nonint get_can_expand
      register: can_expand_fs
      changed_when: False

    - name: Expand Filesystem
      ansible.builtin.command: raspi-config nonint do_expand_rootfs
      when: can_expand_fs.stdout == '0'
      notify: Reboot
  become: yes
  tags: [raspberry_raspi_config, never]
