---
# TODO: Add Molecule test

- name: Install K3s
  become: yes
  block:
    - name: Import prerequisites tasks
      ansible.builtin.include_tasks: prerequisites.yml
    - name: Import install tasks
      ansible.builtin.include_tasks: install.yml
