---
- name: "Download binary - {{ _package }}"
  ansible.builtin.get_url:
    url: "{{ k3s_releases_url }}/k3s{{ '-arm64' if ansible_architecture == 'aarch64' }}"
    checksum: "sha256:{{ k3s_releases_url }}/sha256sum-{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}.txt"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"
  vars:
    k3s_releases_url: "https://github.com/k3s-io/k3s/releases/{{ 'download/' + installer_k3s_version if installer_k3s_version is defined else 'latest/download' }}"

- name: "Copy service file - {{ _package }}"
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: "0644"

- name: "Enable and check service - {{ _package }}"
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: "Create directory .kube - {{ _package }}"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"

- name: "Copy config file to user home directory - {{ _package }}"
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "0600"
