---
- name: "[{{ installer_package }}] Activating cgroup support"
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: Reboot

- name: "[{{ installer_package }}] Flush handlers"
  meta: flush_handlers
