name: Ansible Lint & Molecule Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  ANSIBLE_FORCE_COLOR: 1

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/egvimo/misc

    strategy:
      matrix:
        run:
          - 'ansible-lint'
          - 'ansible-test integration --docker ubuntu2004'
          - 'molecule test --scenario-name docker_wsl'
          - 'molecule test --scenario-name dotfiles'
          - 'molecule test --scenario-name gnome'
          - 'molecule test --scenario-name helper'
          - 'molecule test --scenario-name installer'
          - 'molecule test --scenario-name system'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ansible_collections/egvimo/misc

      - name: Set up Python 3
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: pipenv install --dev

      # TODO Workaround for Ansible lint; remove when fixed
      - name: Remove galaxy.yml
        run: rm galaxy.yml

      - name: Run command
        run: pipenv run ${{ matrix.run }}
