name: Ansible Lint & Molecule Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  ANSIBLE_FORCE_COLOR: 1

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        run:
          - 'ansible-lint'
          - 'molecule test --scenario-name dotfiles'
          - 'molecule test --scenario-name gnome'
          - 'molecule test --scenario-name helper'
          - 'molecule test --scenario-name installer'
          - 'molecule test --scenario-name system'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: sudo apt install pipenv

      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run ${{ matrix.run.name }}
        run: pipenv run ${{ matrix.run.command }}
