---
galaxy_info:
  role_name: installer
  author: egvimo
  description: Role to install different software from different sources

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - installer
